name: Trigger auto deployment for container-app-cv74vls2ppyuo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-cv74vls2ppyuo-AutoDeployTrigger-bca3a689-4d2b-4028-a038-0188d5ea77a2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPCV74VLS2PPYUO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPCV74VLS2PPYUO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPCV74VLS2PPYUO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPCV74VLS2PPYUO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPCV74VLS2PPYUO_REGISTRY_PASSWORD }}
          containerAppName: container-app-cv74vls2ppyuo
          resourceGroup: appspacesragappb4759a73
          imageToBuild: default/container-app-cv74vls2ppyuo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


